[package]
name = "cofi-invoice-authorization"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cofi-billing = { path = "../cofi-billing" }
cofi-invoicing = { path = "../cofi-invoicing" }
cofi-rating-authorization = { path = "../cofi-rating-authorization" }

[dev-dependencies]
cofi-ledger = { path = "../cofi-ledger" }
cofi-metering = { path = "../cofi-metering" }
cofi-rating = { path = "../cofi-rating" }
cofi-subscriptions = { path = "../cofi-subscriptions" }

[lints]
workspace = true
