import test from "node:test";
import assert from "node:assert/strict";

import {
  isGeneratedLockfile,
  siblingPackageJsonPath,
  validateGeneratedLockfile,
} from "./jev-lockfile-validation.mjs";

test("recognizes supported generated lockfiles", () => {
  assert.equal(isGeneratedLockfile("apps/desktop/package-lock.json"), true);
  assert.equal(isGeneratedLockfile("apps/desktop/src-tauri/Cargo.lock"), true);
  assert.equal(isGeneratedLockfile("Cargo.toml"), false);
  assert.equal(
    siblingPackageJsonPath("apps/desktop/package-lock.json"),
    "apps/desktop/package.json",
  );
});

test("validates npm lockfile root metadata against package.json", () => {
  const packageJson = JSON.stringify({
    name: "cofi-desktop",
    version: "1.1.0",
    dependencies: { react: "^19.3.0" },
    devDependencies: { typescript: "^7.0.2" },
  });
  const lock = JSON.stringify({
    name: "cofi-desktop",
    version: "1.1.0",
    lockfileVersion: 3,
    packages: {
      "": {
        name: "cofi-desktop",
        version: "1.1.0",
        dependencies: { react: "^19.3.0" },
        devDependencies: { typescript: "^7.0.2" },
      },
      "node_modules/react": {
        version: "19.3.0",
      },
    },
  });

  const result = validateGeneratedLockfile({
    path: "apps/desktop/package-lock.json",
    content: lock,
    packageJsonContent: packageJson,
  });

  assert.deepEqual(result, {
    kind: "npm",
    lockfile_version: 3,
    package_count: 2,
  });
});

test("rejects npm lockfile metadata drift", () => {
  const packageJson = JSON.stringify({
    name: "cofi-desktop",
    version: "1.1.0",
  });
  const lock = JSON.stringify({
    name: "cofi-desktop",
    version: "1.0.0",
    lockfileVersion: 3,
    packages: {
      "": {
        name: "cofi-desktop",
        version: "1.0.0",
      },
    },
  });

  assert.throws(
    () =>
      validateGeneratedLockfile({
        path: "apps/desktop/package-lock.json",
        content: lock,
        packageJsonContent: packageJson,
      }),
    /version does not match/,
  );
});

test("validates Cargo.lock structure and registry checksums", () => {
  const lock = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "cofi-desktop"
version = "1.1.0"

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0000000000000000000000000000000000000000000000000000000000000000"
`;

  const result = validateGeneratedLockfile({
    path: "apps/desktop/src-tauri/Cargo.lock",
    content: lock,
  });

  assert.deepEqual(result, {
    kind: "cargo",
    lockfile_version: 4,
    package_count: 2,
  });
});

test("rejects registry Cargo.lock entries without checksum", () => {
  const lock = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
`;

  assert.throws(
    () =>
      validateGeneratedLockfile({
        path: "Cargo.lock",
        content: lock,
      }),
    /missing checksum/,
  );
});
