import test from "node:test";
import assert from "node:assert/strict";

import {
  isDeterministicBinaryAsset,
  isGeneratedLockfile,
  siblingPackageJsonPath,
  validateBinaryAsset,
  validateGeneratedLockfile,
} from "./jev-lockfile-validation.mjs";

test("recognizes supported generated lockfiles", () => {
  assert.equal(isGeneratedLockfile("apps/desktop/package-lock.json"), true);
  assert.equal(isGeneratedLockfile("apps/desktop/src-tauri/Cargo.lock"), true);
  assert.equal(isGeneratedLockfile("Cargo.toml"), false);
  assert.equal(
    siblingPackageJsonPath("apps/desktop/package-lock.json"),
    "apps/desktop/package.json",
  );
});

test("validates npm lockfile root metadata against package.json", () => {
  const packageJson = JSON.stringify({
    name: "cofi-desktop",
    version: "1.1.0",
    dependencies: { react: "^19.3.0" },
    devDependencies: { typescript: "^7.0.2" },
  });
  const lock = JSON.stringify({
    name: "cofi-desktop",
    version: "1.1.0",
    lockfileVersion: 3,
    packages: {
      "": {
        name: "cofi-desktop",
        version: "1.1.0",
        dependencies: { react: "^19.3.0" },
        devDependencies: { typescript: "^7.0.2" },
      },
      "node_modules/react": {
        version: "19.3.0",
      },
    },
  });

  const result = validateGeneratedLockfile({
    path: "apps/desktop/package-lock.json",
    content: lock,
    packageJsonContent: packageJson,
  });

  assert.deepEqual(result, {
    kind: "npm",
    lockfile_version: 3,
    package_count: 2,
  });
});

test("rejects npm lockfile metadata drift", () => {
  const packageJson = JSON.stringify({
    name: "cofi-desktop",
    version: "1.1.0",
  });
  const lock = JSON.stringify({
    name: "cofi-desktop",
    version: "1.0.0",
    lockfileVersion: 3,
    packages: {
      "": {
        name: "cofi-desktop",
        version: "1.0.0",
      },
    },
  });

  assert.throws(
    () =>
      validateGeneratedLockfile({
        path: "apps/desktop/package-lock.json",
        content: lock,
        packageJsonContent: packageJson,
      }),
    /version does not match/,
  );
});

test("validates Cargo.lock structure and registry checksums", () => {
  const lock = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "cofi-desktop"
version = "1.1.0"

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0000000000000000000000000000000000000000000000000000000000000000"
`;

  const result = validateGeneratedLockfile({
    path: "apps/desktop/src-tauri/Cargo.lock",
    content: lock,
  });

  assert.deepEqual(result, {
    kind: "cargo",
    lockfile_version: 4,
    package_count: 2,
  });
});

test("rejects registry Cargo.lock entries without checksum", () => {
  const lock = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
`;

  assert.throws(
    () =>
      validateGeneratedLockfile({
        path: "Cargo.lock",
        content: lock,
      }),
    /missing checksum/,
  );
});

test("recognizes deterministic desktop icon assets", () => {
  assert.equal(isDeterministicBinaryAsset("icons/128x128.png"), true);
  assert.equal(isDeterministicBinaryAsset("icons/icon.ico"), true);
  assert.equal(isDeterministicBinaryAsset("icons/icon.icns"), true);
  assert.equal(isDeterministicBinaryAsset("icons/source.svg"), false);
});

test("validates PNG signature and dimensions", () => {
  const png = Buffer.alloc(24);
  Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]).copy(png, 0);
  png.write("IHDR", 12, "ascii");
  png.writeUInt32BE(128, 16);
  png.writeUInt32BE(128, 20);

  assert.deepEqual(
    validateBinaryAsset({ path: "icons/128x128.png", content: png }),
    { kind: "png", bytes: 24, width: 128, height: 128 },
  );
});

test("validates ICO and ICNS structural headers", () => {
  const ico = Buffer.alloc(6);
  ico.writeUInt16LE(0, 0);
  ico.writeUInt16LE(1, 2);
  ico.writeUInt16LE(3, 4);
  assert.deepEqual(
    validateBinaryAsset({ path: "icons/icon.ico", content: ico }),
    { kind: "ico", bytes: 6, image_count: 3 },
  );

  const icns = Buffer.alloc(8);
  icns.write("icns", 0, "ascii");
  icns.writeUInt32BE(8, 4);
  assert.deepEqual(
    validateBinaryAsset({ path: "icons/icon.icns", content: icns }),
    { kind: "icns", bytes: 8 },
  );
});

test("rejects malformed binary assets", () => {
  assert.throws(
    () => validateBinaryAsset({ path: "icons/bad.png", content: Buffer.alloc(24) }),
    /invalid PNG structure/,
  );
  assert.throws(
    () => validateBinaryAsset({ path: "icons/bad.ico", content: Buffer.alloc(6) }),
    /invalid ICO header/,
  );
  assert.throws(
    () => validateBinaryAsset({ path: "icons/bad.icns", content: Buffer.alloc(8) }),
    /invalid ICNS header/,
  );
});
